# Generated by Django 5.0.3 on 2024-03-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0005_pagecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
