# Generated by Django 5.0.3 on 2024-03-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
